#ifndef _APP_PARAMS_THEMEPARAMETERS_H_
#define _APP_PARAMS_THEMEPARAMETERS_H_

//STL
#include <string>

// EPG
#include <epg/params/ParametersT.h>
#include <epg/SingletonT.h>



	enum TH_PARAMETERS{
		DB_CONF_FILE,
		WORKING_SCHEMA,
		EDGE_TABLE_INIT,
		EDGE_TABLE_INIT_BASE,
		W_TAG_NAME,
		EDGE_FICTITIOUS_NAME,
		WATERCOURSE_AREA_TABLE,
		WATERCOURSE_AREA_TABLE_BASE,
		STANDING_WATER_TABLE,
		STANDING_WATER_TABLE_BASE,
		MATCHED_WATERCOURSE_AREA_TABLE,
		MATCHED_WATERCOURSE_AREA_TABLE_BASE,
		MATCHED_STANDING_WATER_TABLE,
		MATCHED_STANDING_WATER_TABLE_BASE,
		BOUNDARY_SMOOTHED_TABLE,
		LANDMASK_TABLE,
		LAND_COVER_TYPE_NAME,
		TYPE_LAND_AREA,
		FORM_OF_WAY_NAME,
		COUNTRY_CODE_W,
		NATIONAL_IDENTIFIER_NAME,

		CC_DIST_THRESHOLD,

		CFC_SNAP_DIST,

		FFF_RATIO,

		JM_MAX_DIST,
		JM_MAX_ANGLE,

		CLA_SURFACE_WIDTH,
		CLA_FICTITIOUS_RATIO_THRESHOLD,
		CLA_FICTITIOUS_LENGTH_THRESHOLD,
		CLA_CL_LENGTH_THRESHOLD,
		CLA_CL_MIN_RATIO_IN_AREA,
		CLA_CL_LENGTH_THRESHOLD_2,
		CLA_CL_MIN_RATIO_IN_AREA_2,

		CP_TABLE,
		CL_TABLE,
		CP_TABLE_SUFFIX,
		CL_TABLE_SUFFIX,
		CF_STATUS,

		CFG_BOUNDARY_ANGLE_THRESHOLD,

		CP_MERGE_DIST_CP,
		CP_MERGE_DIST_TRACTOR_CP,
		CP_FORM_OF_WAY_EXCEPTION,
		CP_BUFFER_DIST,
		CP_INTERSECTED_CL_DIST,
		CP_UNDERSHOOT_DIST,
		CP_CP_2_CL_SNAP_DIST,
		CP_VERTEX_CL_SNAP_DIST,

		CL_BUFFER_DIST,
		CL_THRESHOLD_NO_CL,
		CL_RATIO_IN_BUFFER,
		CL_SNAP_ON_VERTEX_BORDER_DIST,
		CL_CL_CLOSEST_MAX_DIST,
		CL_BORDER_MAX_ANGLE,
		CL_EDGE_MAX_ANGLE,
		CL_MIN_LENGTH,
		CL_CL_INTERSECTED_DIST,
		CL_MERGE_CL_DIST,
		CL_EDGE_MAX_DIST,
		CL_SNAP_PROJ_CL_2_EDGE_DIST,
		CL_CL_2_MERGE_MIN_LENGTH,

		LIST_ATTR_JSON,
		LIST_ATTR_W,

		SQL_FILTER_EDGES_2_GENERATE_CF,

		EC_LANDMASK_BUFFER,
		EC_SNAP_DIST,
		EC_SNAP_2_EDGE_END_DIST,

		ECL_SQL_FILTER,
		ECL_SLIM_SURFACE_WIDTH,
		ECL_ARTIFACT_WIDTH,
		ECL_SLIM_SURFACE_MAX_AREA,
		ECL_SLIM_SURFACE_MAX_NB_POINTS,
		ECL_ANTENNA_RATIO_THRESHOLD,
		ECL_ANTENNA_RATIO_WITH_BUFFER_THRESHOLD,
		ECL_LANDMASK_BUFFER,
		ECL_ANTENNA_MIN_LENGTH,
		ECL_ANTENNA_MIN_LENGTH_IN_COUNTRY,
		ECL_PARALELLE_EDGE_MAX_DIST,
		ECL_ANTENNA_MIN_DIST_2_NEIGHBOR,
		ECL_TINY_EDGE_MAX_LENGTH
	};

namespace app{
namespace params{

	class ThemeParameters : public epg::params::ParametersT< TH_PARAMETERS >
	{
		typedef  epg::params::ParametersT< TH_PARAMETERS > Base;

		public:

			/// \brief
			ThemeParameters();

			/// \brief
			~ThemeParameters();

			/// \brief
			virtual std::string getClassName()const;

	};

	typedef epg::Singleton< ThemeParameters >   ThemeParametersS;

}
}

#endif