#ifndef _APP_PARAMS_THEMEPARAMETERS_H_
#define _APP_PARAMS_THEMEPARAMETERS_H_

//STL
#include <string>

//EPG
#include <epg/params/ParametersT.h>
#include <epg/SingletonT.h>



	enum TN_PARAMETERS{
		DB_CONF_FILE,
		EDGE_TABLE_INIT,
		COUNTRY_CODE_W,
		W_TAG,
		
		BOUNDARY_SMOOTHED_TABLE,
		LANDMASK_TABLE,
		LAND_COVER_TYPE,
		TYPE_LAND_AREA,
		FORM_OF_WAY,
		SNAP_DIST,
		ANGLE_MAX_2_CUT_BORDER,
		CP_TABLE,
		CL_TABLE,
		CP_TABLE_SUFFIX,
		CL_TABLE_SUFFIX,
		CF_STATUS,

		CP_MERGE_DIST_CP,
		CP_MERGE_DIST_TRACTOR_CP,
		CP_VALUE_FORMWAY_BIGDIST2MERGE,
		CP_BUFFER_DIST,
		CP_INTERSECTED_CL_DIST,
		CP_UNDERSHOOT_DIST,
		CP_CP_2_CL_SNAP_DIST,
		CP_VERTEX_CL_SNAP_DIST,

		CL_BUFFER_DIST,
		CL_THRESHOLD_NO_CL,
		CL_RATIO_IN_BUFFER,
		CL_SNAP_ON_VERTEX_BORDER_DIST,
		CL_CL_CLOSEST_MAX_DIST,
		CL_BORDER_MAX_ANGLE,
		CL_EDGE_MAX_ANGLE,
		CL_CL_INTERSECTED_DIST,
		CL_MERGE_CL_DIST,
		CL_EDGE_MAX_DIST,
		CL_SNAP_PROJ_CL_2_EDGE_DIST,
		CL_CL_2_MERGE_MIN_LENGTH,

		LIST_ATTR_TO_CONCAT,
		LIST_ATTR_JSON,
		LIST_ATTR_W,
		SQL_FILTER_EDGES_2_GENERATE_CF,

		EC_LANDMASK_BUFFER,
		EC_SNAP_DIST,
		EC_SNAP_2_EDGE_END_DIST,

		ECL_SQL_FILTER,
		ECL_SLIM_SURFACE_WIDTH,
		ECL_ARTIFACT_WIDTH,
		ECL_SLIM_SURFACE_MAX_AREA,
		ECL_SLIM_SURFACE_MAX_NB_POINTS,
		ECL_ANTENNA_RATIO_THRESHOLD,
		ECL_ANTENNA_RATIO_WITH_BUFFER_THRESHOLD,
		ECL_LANDMASK_BUFFER,
		ECL_ANTENNA_MIN_LENGTH,
		ECL_ANTENNA_MIN_LENGTH_IN_COUNTRY,
		ECL_PARALELLE_EDGE_MAX_DIST,
		ECL_ANTENNA_MIN_DIST_2_NEIGHBOR,
		ECL_TINY_EDGE_MAX_LENGTH,

		DIST_MAX_JUNCTIONS,
		ANGLE_MAX_ORIENTATION_EDGES
	};

namespace app{
namespace params{

	class ThemeParameters : public epg::params::ParametersT< TN_PARAMETERS >
	{
		typedef  epg::params::ParametersT< TN_PARAMETERS > Base;

		public:

			/// \brief
			ThemeParameters();

			/// \brief
			~ThemeParameters();

			/// \brief
			virtual std::string getClassName()const;

	};

	typedef epg::Singleton< ThemeParameters >   ThemeParametersS;

}
}

#endif