FROM libepg

RUN apt-get update -y \
 && apt-get -y install g++ \
 && apt-get -y install gcc \
 && apt-get -y install cmake \
 && apt-get -y install make \
 && apt-get -y install gdb \
 && rm -rf /var/lib/apt/lists/*

ENV APP_DIR_SRC=/usr/local/src/net_matching/                                                     

WORKDIR $APP_DIR_SRC