[params]
DB_CONF_FILE                              =/usr/local/src/net_matching/config/db_conf_v6.ini
WORKING_SCHEMA                            =
EDGE_TABLE_INIT                           =watercourse_link_w_be_fr_test
EDGE_TABLE_INIT_BASE                      =watercourse_link_w
W_TAG_NAME                                =w_tag
EDGE_FICTITIOUS_NAME                      =fictitious
WATERCOURSE_AREA_TABLE                    =watercourse_area_w_be_fr_20250213
WATERCOURSE_AREA_TABLE_BASE               =watercourse_area_w
STANDING_WATER_TABLE                      =standing_water_w_be_fr_20250213
STANDING_WATER_TABLE_BASE                 =standing_water_w
MATCHED_WATERCOURSE_AREA_TABLE            =_399_watercourse_area_w_be_nl_20250120
MATCHED_WATERCOURSE_AREA_TABLE_BASE       =_399_watercourse_area_w
MATCHED_STANDING_WATER_TABLE              =_399_standing_water_w_be_nl_20250120
MATCHED_STANDING_WATER_TABLE_BASE         =_399_standing_water_w
BOUNDARY_SMOOTHED_TABLE                   =
LANDMASK_TABLE                            =au.administrative_unit_area_1
LAND_COVER_TYPE_NAME                      =land_cover_type 
TYPE_LAND_AREA                            =land_area
FORM_OF_WAY_NAME                          =form_of_way
COUNTRY_CODE_W                            =
NATIONAL_IDENTIFIER_NAME                  =w_national_identifier

####connectivity correction
CC_DIST_THRESHOLD                         =0.1

####cf connection
CFC_SNAP_DIST                             =1

####fill fictitious field
FFF_RATIO                                 =0.5

###### junction matching 
JM_MAX_DIST                               =10
JM_MAX_ANGLE                              =30

####cl in area generation
CLA_SURFACE_WIDTH                         =50
CLA_FICTITIOUS_RATIO_THRESHOLD            =0.1
CLA_FICTITIOUS_LENGTH_THRESHOLD           =20
CLA_CL_LENGTH_THRESHOLD                   =30
CLA_CL_MIN_RATIO_IN_AREA                  =0.33
CLA_CL_LENGTH_THRESHOLD_2                 =2
CLA_CL_MIN_RATIO_IN_AREA_2                =0.33

####connecting features
CP_TABLE                                  =
CL_TABLE                                  =
CP_TABLE_SUFFIX                           =_cp
CL_TABLE_SUFFIX                           =_cl
CF_STATUS                                 =cf_status
 
####cf generation
CFG_BOUNDARY_ANGLE_THRESHOLD              =180
##cp
CP_MERGE_DIST_CP                          =5
CP_MERGE_DIST_TRACTOR_CP                  =12
CP_FORM_OF_WAY_EXCEPTION                  =
CP_BUFFER_DIST                            =5
CP_FROM_CL_FROM_BORDER_PAIRING_DIST       =5
CP_UNDERSHOOT_DIST                        =35
##cl
CL_BUFFER_DIST                            =20
CL_THRESHOLD_NO_CL                        =0.1
CL_RATIO_IN_BUFFER                        =0.6
CL_SNAP_ON_VERTEX_BORDER_DIST             =2
CL_CL_CLOSEST_MAX_DIST                    =2
CL_BORDER_MAX_ANGLE                       =45
CL_EDGE_MAX_ANGLE                         =45
CL_MIN_LENGTH                             =10
CL_CL_INTERSECTED_DIST                    =10
CL_MERGE_CL_DIST                          =1
CL_EDGE_MAX_DIST                          =14
CL_SNAP_PROJ_CL_2_EDGE_DIST               =0.1
CL_CL_2_MERGE_MIN_LENGTH                  =5

######
LIST_ATTR_JSON                            =name
LIST_ATTR_W                               =objectid/geom/begin_lifespan_version/end_lifespan_version/w_step/net_type/cf_status/w_scale/w_release
##### filtre edges
SQL_FILTER_EDGES_2_GENERATE_CF            =

###### edge connector
EC_LANDMASK_BUFFER                        =20
EC_SNAP_DIST                              =10
EC_SNAP_2_EDGE_END_DIST                   =1

###### cleaning
ECL_SQL_FILTER                            =
ECL_SLIM_SURFACE_WIDTH                    =5
ECL_ARTIFACT_WIDTH                        =2
ECL_SLIM_SURFACE_MAX_AREA                 =100000000
ECL_SLIM_SURFACE_MAX_NB_POINTS            =10000
ECL_ANTENNA_RATIO_THRESHOLD               =0
ECL_ANTENNA_RATIO_WITH_BUFFER_THRESHOLD   =0.70
ECL_LANDMASK_BUFFER                       =20
ECL_ANTENNA_MIN_LENGTH                    =20
ECL_ANTENNA_MIN_LENGTH_IN_COUNTRY         =75
ECL_PARALELLE_EDGE_MAX_DIST               =0.1
ECL_ANTENNA_MIN_DIST_2_NEIGHBOR           =5
ECL_TINY_EDGE_MAX_LENGTH                  =0.2

[at#ch]
COUNTRY_CODE_W                            =at#ch

[at#cz]
COUNTRY_CODE_W                            =at#cz

[at#li]
COUNTRY_CODE_W                            =at#li

[be#fr]
COUNTRY_CODE_W                            =be#fr

[be#lu]
COUNTRY_CODE_W                            =be#lu

[be#nl]
COUNTRY_CODE_W                            =be#nl
ECL_SLIM_SURFACE_WIDTH                    =6

[ch#fr]
COUNTRY_CODE_W                            =ch#fr

[es#fr]
COUNTRY_CODE_W                            =es#fr

[fr#lu]
COUNTRY_CODE_W                            =fr#lu
